name: 'release'
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2.3.4
    - uses: "marvinpinto/action-automatic-releases@latest@v1.2.1"
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
